-- CREATE A SIMPLE TABLE FOR RATING


CREATE TABLE RATER (
	USERID VARCHAR(50),
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	NAME VARCHAR(50) NOT NULL,
	JOIN_DATE TIMESTAMP DEFAULT(NOW()),
	TYPE VARCHAR(20),
	PASSWORD VARCHAR(255),
	REPUTATION INT,
	PRIMARY KEY(USERID),
	CONSTRAINT CHECK_REPUTAION CHECK (REPUTATION BETWEEN 1 AND 5)
);

CREATE TABLE RATING (
	USERID VARCHAR(50),
	DATE TIMESTAMP DEFAULT(NOW()) UNIQUE,
	PRICE INT,
	FOOD INT,
	MOOD INT,
	STAFF INT,
	COMMENTS VARCHAR(100),
	RESTAURANTID VARCHAR(20),

	PRIMARY KEY (DATE),
	FOREIGN KEY (USERID) REFERENCES RATER (USERID),
	CONSTRAINT CHECK_INTERVAL_RATING CHECK (    (PRICE BETWEEN 1 AND 5)
																					AND (FOOD  BETWEEN 1 AND 5)
																					AND (MOOD  BETWEEN 1 AND 5)
																					AND (STAFF BETWEEN 1 AND 5))
	-- FOREIGN KEY (DATE) REFERENCES RESTAURANT (DATE_)
);


CREATE TABLE RESTAURANT (
	RESTAURANTID VARCHAR(20),
	NAME VARCHAR(100),
	TYPE VARCHAR(20),
	URL VARCHAR(100),

	PRIMARY KEY (RESTAURANTID)
);

CREATE TABLE LOCATION (
	LOCATIONID VARCHAR(20),
	FIRSTOPEN_DATE DATE,
	MANAGER_NAME VARCHAR(20),
	PHONE_NUMBER VARCHAR(20),
	STREET_ADDRESS VARCHAR(100),
	HOUR_OPEN TIME,
	HOUR_CLOSE TIME,
	RESTAURANTID VARCHAR(20),

	PRIMARY KEY(LOCATIONID),
	FOREIGN KEY (RESTAURANTID) REFERENCES RESTAURANT (RESTAURANTID)
);

CREATE TABLE MENUITEM (
	ITEMID INT,
	NAME VARCHAR(50),
	TYPE VARCHAR(20),
	CATEGORY VARCHAR(20),
	DESCRIPTION VARCHAR(100),
	PRICE NUMERIC(100,2),
	RESTAURANTID VARCHAR(20),

	PRIMARY KEY (ITEMID),
	FOREIGN KEY (RESTAURANTID) REFERENCES RESTAURANT (RESTAURANTID)
);

CREATE TABLE RATINGITEM (
	USERID VARCHAR(50),
	DATE TIMESTAMP,
	ITEMID INT,
	GRADE NUMERIC(8,2),
	COMMENTS VARCHAR(1000),

	FOREIGN KEY (USERID) REFERENCES RATER (USERID),
	FOREIGN KEY (ITEMID) REFERENCES MENUITEM (ITEMID),
  FOREIGN KEY (DATE)   REFERENCES RATING (DATE),
	CONSTRAINT CHECK_GRADE CHECK (GRADE BETWEEN 1.0 AND 5.0),
	PRIMARY KEY (USERID, DATE, ITEMID)
);
