-- Restaurant and menu queries

-- a
SELECT *
FROM RESTAURANT AS RES NATURAL INNER JOIN LOCATION AS LOC
WHERE RES.RESTAURANTID = USER_SPECIFIED_id;

SELECT *
FROM RESTAURANT AS RES NATURAL INNER JOIN LOCATION AS LOC
WHERE RES.NAME = chosen_name;

-- b
SELECT CATEGORY,NAME,DESCRIPTION,PRICE
FROM MENUITEM AS MI  NATURAL INNER JOIN RESTAURANT AS RES
WHERE RES.NAME = chosen_name
GROUP BY MI.CATEGORY;

-- c
SELECT RES.NAME,TYPE,HOUR_OPEN,HOUR_CLOSE,STREET_ADDRESS,PHONE_NUMBER,MANAGER_NAME,FIRSTOPEN_DATE
FROM RESTAURANT AS RES NATURAL INNER JOIN LOCATION AS LOC
WHERE RES.TYPE = USER_SPECIFIED_tp;

SELECT CATEGORY,NAME,DESCRIPTION,PRICE
FROM MENUITEM AS MI NATURAL INNER JOIN RESTAURANT AS RES
WHERE MI.RESTAURANTID = USER_SPECIFIED_id
GROUP BY MI.CATEGORY;

-- d
SELECT RES.NAME,MAX(PRICE) AS MAX_PRICE,MANAGER_NAME,HOUR_OPEN,HOUR_CLOSE,HOUR_CLOSE
FROM MENUITEM AS MI NATURAL INNER JOIN RESTAURANT AS RES NATURAL INNER JOIN LOCATION AS LOC
GROUP BY RES.NAME;

-- e
SELECT RES.TYPE,MI.CATEGORY,AVG(PRICE)
FROM RESTAURANT AS RES NATURAL INNER JOIN MENUITEM AS MI
GROUP BY RES.TYPE,MI.TYPE;

-- Ratings and Restaurant

-- f
-- ????

-- g
SELECT RES.NAME,RES.TYPE,LOC.PHONE_NUMBER
FROM RESTAURANT AS RES NATURAL INNER JOIN LOCATION AS LOCATION NATURAL INNER JOIN MENUITEM AS MI
WHERE MI.ITEMID IN (SELECT ITEMID FROM RATINGITEM WHERE (DATE >= '01/01/2015' OR DATE <= '31/01/2015'));

-- h
SELECT RES.NAME,LOC.HOUR_OPEN,LOC.HOUR_CLOSE
FROM RESTAURANT AS RES NATURAL INNER JOIN LOCATION AS LOC NATURAL INNER JOIN RATING AS RA
WHERE RA.STAFF < (SELECT MIN(PRICE) FROM RATING WHERE USERID = ID)
AND RA.STAFF < (SELECT MIN(MOOD) FROM RATING WHERE USERID = ID)
AND RA.STAFF < (SELECT MIN(FOOD) FROM RATING WHERE USERID = ID)
AND RA.STAFF < (SELECT MIN(STAFF) FROM RATING WHERE USERID = ID);

-- i
SELECT *
FROM RESTAURANT NATURAL INNER JOIN RATING
GROUP BY TYPE
HAVING MAX(FOOD);

-- j POPULARITY IS BASED ON NUMBER OF REVIEWS
SELECT TYPE, COUNT(*) AS TOTAL_REVIEWS
FROM RESTAURANT NATURAL INNER JOIN RATING
GROUP BY TYPE
ORDER BY TOTAL_REVIEWS;
